TypZespolone.o: TypZespolone.c
	gcc -Wall -std=c99 -pedantic -c -lm TypZespolone.c

zespolone.o: zespolone.c
	gcc -Wall -std=c99 -pedantic -c zespolone.c

zespolone.x: zespolone.o TypZespolone.o
	gcc -Wall -std=c99 -pedantic -o zespolone.x zespolone.o TypZespolone.o

